name: Build

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies using nuget
        run: nuget restore

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild /p:Configuration=Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Netease-Music-Proxy-${{ github.sha }}
          path: .\Netease-Music-Proxy\bin\Release\Netease-Music-Proxy.exe

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
      
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .\Netease-Music-Proxy\bin\Release\Netease-Music-Proxy.exe
          asset_name: Netease-Music-Proxy-${{ github.ref_name }}.exe
          asset_content_type: application/x-msdownload

      - name: Notify
        uses: niniyas/ntfy-action@master
        with:
          url: 'https://ntfy.sh'
          topic: 'netease-music-proxy-github-actions-done'
          title: 'Netease-Music-Proxy ${{ github.ref_name }} build done'
          details: 'Release URL: ${{ steps.create_release.outputs.html_url }}'
